Bug 581775 - Update tycho to 3.0.4, Java to 17. Add target 2023-03
Add target platform 2023-03.

Update Java to 17 in target platforms 2012-09 onwards as per Eclipse
requirement.

Update tycho to latest 3.0.4.

Oomph setup:Project URLs changed to 'https' instead of 'http' to avoid
error: cvc-elt.1.a: Cannot find the declaration of element 'project'.

Change-Id: If3dbbecbe4e31e7d199a31363f0c43acda53539f
Signed-off-by: Aparna Argade <aprsac@yahoo.com>